version: '3'
services:
  rails:
    build: ./problem/rugmi
    ports:
      - '10007:3000'
    volumes:
      - ./problem/rugmi:/rails
    links:
      - db
    command: >
      wait-for db:3306 -t 180 -- sh -c "
        RAILS_DATABASE_USERNAME=root RAILS_DATABASE_PASSWORD=uHrrsLzb6QWIm5CC bundle exec rake db:create db:migrate db:seed &&
        bundle exec rails server --binding 0.0.0.0
      "
    environment:
      RAILS_ENV: production
      RAILS_DATABASE_USERNAME: rugmi
      RAILS_DATABASE_PASSWORD: very_very_long_and_secure_password_that_you_cannot_guess_for_the_evil
      RAILS_DATABASE_HOST: db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: rugmi
      MYSQL_PASSWORD: very_very_long_and_secure_password_that_you_cannot_guess_for_the_evil
      MYSQL_ROOT_PASSWORD: uHrrsLzb6QWIm5CC
