version: '3'
services:
  rails:
    build: .
    ports:
      - '10007:3000'
    volumes:
      - .:/rails
    links:
      - db
    command: >
      wait-for db:3306 -t 180 -- sh -c "
        RAILS_DATABASE_USERNAME=root RAILS_DATABASE_PASSWORD=*censored* bundle exec rake db:create db:migrate db:seed &&
        bundle exec rails server --binding 0.0.0.0
      "
    environment:
      RAILS_ENV: production
      RAILS_DATABASE_USERNAME: rugmi
      RAILS_DATABASE_PASSWORD: *censored*
      RAILS_DATABASE_HOST: db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: rugmi
      MYSQL_PASSWORD: *censored*
      MYSQL_ROOT_PASSWORD: *censored*
