version: '2.4'

services:
    ctf:
        build: ./
        restart: always
        ports:
            - "34000:34000"
        expose:
            - "34000"
        mem_limit: 100m
        read_only: true
