version: '2.4'

services:
    ctf:
        build: ./
        restart: always
        ports:
            - "30001:30001"
        expose:
            - "30001"
        mem_limit: 100m
        read_only: true
