version: '2.4'

services:
    ctf:
        build: ./
        restart: always
        ports:
            - "33000:33000"
        expose:
            - "33000"
        mem_limit: 100m
        read_only: true
